"""Negative control for the F2 probe: extract the PRE-085 FetchRemote verbatim
from git (src/plugins/mdview/webglue.cpp at 7f50632, the commit before
feature 085) and write it as obj/remotefetch_pre085.cpp, renamed to
MdFetchRemote so fetch_main.cpp links against it unchanged.

The probe must FAIL against this file (identification, status, redirect
cookie) - that is what shows the checks can fire.

Usage: python extract_pre085.py <out.cpp>
"""

import subprocess
import sys

BASE = "7f50632"


def main():
    out = sys.argv[1]
    src = subprocess.run(["git", "show", BASE + ":src/plugins/mdview/webglue.cpp"],
                         capture_output=True, check=True).stdout.decode("utf-8-sig")
    start = src.index("static bool FetchRemote(")
    end = src.index("return ok && !out.empty();", start)
    end = src.index("}", end) + 1
    body = src[start:end].replace("static bool FetchRemote(", "bool MdFetchRemote(", 1)
    with open(out, "w", encoding="utf-8", newline="\r\n") as f:
        f.write("// generated by extract_pre085.py - the pre-085 FetchRemote, verbatim\n")
        f.write("#include <windows.h>\n#include <winhttp.h>\n#include \"remotefetch.h\"\n\n")
        f.write(body)
        f.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
